JGEN = ./build_job.py
SECS = 1800

m14: $(JGEN)
	$(JGEN) 5 14 $(SECS)
	$(JGEN) 6 14 $(SECS)
	$(JGEN) 7 14 $(SECS)
	$(JGEN) 8 14 $(SECS)
	$(JGEN) 9 14 $(SECS)
	$(JGEN) 10 14 $(SECS)
	$(JGEN) 11 14 $(SECS)
	$(JGEN) 12 14 $(SECS)
	$(JGEN) 13 14 $(SECS)
	$(JGEN) 15 14 $(SECS)
	$(JGEN) 16 14 $(SECS)
	$(JGEN) 17 14 $(SECS)
	$(JGEN) 18 14 $(SECS)
	$(JGEN) 19 14 $(SECS)
	$(JGEN) 20 14 $(SECS)
	$(JGEN) 21 14 $(SECS)
	$(JGEN) 22 14 $(SECS)
	$(JGEN) 23 14 $(SECS)

clean:
	rm -f *~
	rm -f *.job
